### ISSUE TITLE
설정 모달 Header 크기

### ISSUE THREAD

**Issue by MaengMaeng** [MaengMaeng/MyTime#22]
![image](https://user-images.githubusercontent.com/31842031/101547012-f62ad780-39ec-11eb-863a-ed4a1c4077c8.png)

헤더의 크기가 커서 border가 모달을 뚫고 나옴

**Comment by MaengMaeng** [comment]
### 이유
```css
.modal-header{
    width: 100%;

    padding: 4px;
    border-bottom: 1px solid #BBB;
}
```
- box-sizing은 기본적으로 content-box이다. 이 경우 width:100%, padding, border의 크기를 모두 더해서 그리게 된다. 그래서 modal의 크기인 400px을 넘어서 408px의 헤더가 그려졌다.

### 해결방법
```
1. box-sizing:border-box
2. width:auto
```
기본적으로 width는 auto이므로 width를 지워줌으로서 간단하게 해결했다.
